# Generated by Django 4.0.3 on 2022-04-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFTcore', '0002_coursecard_layergroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseCard',
        ),
    ]
